name: houzee
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.6
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1
  flutter_svg_provider: ^1.0.7
  intl: ^0.19.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Acme
      fonts: 
        - asset: assets/fonts/AcmeRegular.ttf
          weight: 400
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanLight.ttf
          weight: 300
        - asset: assets/fonts/RobotoItalicThin.ttf
          weight: 100
        - asset: assets/fonts/RobotoItalicRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoItalicLight.ttf
          weight: 300
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
    - family: Aladin
      fonts: 
        - asset: assets/fonts/AladinRegular.ttf
          weight: 400
    - family: Aclonica
      fonts: 
        - asset: assets/fonts/AclonicaRegular.ttf
          weight: 400
